version: '3.5'
services:
  app:
    container_name: j3app
    image: meteor
    working_dir: /var/www
    ports:
      - 3000:3000
    volumes:
      - .:/var/www
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
    # entrypoint: ['/bin/sh', './docker/entrypoint.sh']
    # environment:
    # METEOR_ALLOW_SUPERUSER: 'true'
    command: mupx deploy --allow-superuser
    tty: false
    restart: on-failure
